name: post-benchmarks
runs:
  using: composite
  steps:
  - uses: actions/upload-artifact@v3.1.1
    with:
      path: "/tmp/benchmark-results"
  - name: Send benchmark report to visualisation
    run: echo "skip this job, we don't have a visualisation yet"
#    run: |-
#      set +e
#      set +o pipefail
#      ./build_tools/benchmark_log_tool.py --tsvfile /tmp/benchmark-results/report.tsv --esdocument https://search-rocksdb-bench-k2izhptfeap2hjfxteolsgsynm.us-west-2.es.amazonaws.com/bench_test3_rix/_doc
#      true
#    shell: bash