name: windows-build-steps
runs:
  using: composite
  steps:
  - uses: actions/checkout@v3.5.0
  - name: Install thirdparty dependencies
    run: |-
      mkdir $Env:THIRDPARTY_HOME
      cd $Env:THIRDPARTY_HOME
      echo "Building Snappy dependency..."
      curl https://github.com/google/snappy/archive/refs/tags/1.1.8.zip -O snappy-1.1.8.zip
      unzip -q snappy-1.1.8.zip
      cd snappy-1.1.8
      mkdir build
      cd build
      & $Env:CMAKE_BIN -G "$Env:CMAKE_GENERATOR" -j4 ..
      msbuild.exe Snappy.sln -maxCpuCount -property:Configuration=Debug -property:Platform=x64
    shell: bash
  - name: Build RocksDB
    run: |-
      mkdir build
      cd build
      & $Env:CMAKE_BIN -G "$Env:CMAKE_GENERATOR" -DCMAKE_BUILD_TYPE=Debug -DOPTDBG=1 -DPORTABLE=1 -DSNAPPY=1 -DJNI=1 -j4 ..
      cd ..
      echo "Building with VS version: $Env:CMAKE_GENERATOR"
      msbuild.exe build/rocksdb.sln -maxCpuCount -property:Configuration=Debug -property:Platform=x64
    shell: bash
  - name: Test RocksDB
    run: build_tools\run_ci_db_test.ps1 -SuiteRun arena_test,db_basic_test,db_test,db_test2,db_merge_operand_test,bloom_test,c_test,coding_test,crc32c_test,dynamic_bloom_test,env_basic_test,env_test,hash_test,random_test -Concurrency 4
    shell: powershell.exe