name: build-for-benchmarks
runs:
  using: composite
  steps:
  - uses: "./.github/actions/pre-steps"
  - name: Linux build for benchmarks
    run: |
      cd /__w/encfs/encfs/rocksdb
      make V=1 J=4 -j4 release
    shell: bash