name: build-for-benchmarks
runs:
  using: composite
  steps:
  - uses: "./.github/actions/pre-steps"
  - name: Linux build for benchmarks
    run: ROCKSDB_PLUGINS="encfs" make V=1 J=4 -j4 release
    shell: bash