name: jobs-macos
on: [pull_request]
jobs:
  build-macos:
    runs-on: macos-11
    env:
      ROCKSDB_DISABLE_JEMALLOC: 1
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 12.5.1
    - uses: "./.github/actions/increase-max-open-files-on-macos"
    - uses: "./.github/actions/install-gflags-on-macos"
    - uses: "./.github/actions/pre-steps-macos"
    - name: Build
      working-directory: /Users/runner/work/encfs/encfs/rocksdb
      run: echo "skip this job"
      # TODO(yingchun): resolve the link error
#      ar: creating archive librocksdb_env_basic_test.a
#      Undefined symbols for architecture x86_64:
#          "encfs_reg", referenced from:
#                         -u command line option
#                         (maybe you meant: _encfs_reg)
#      ld: symbol(s) not found for architecture x86_64
#      clang:
#        error: linker command failed with exit code 1 (use -v to see invocation)
#      make: *** [ librocksdb_debug.8.5.3.dylib ] Error 1
#      make: *** Waiting for unfinished jobs....
#      run: ulimit -S -n `ulimit -H -n` && OPT=-DCIRCLECI make V=1 J=4 -j4 all
    - uses: "./.github/actions/post-steps"
  build-macos-test-0:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 12.5.1
    - uses: "./.github/actions/increase-max-open-files-on-macos"
    - uses: "./.github/actions/install-cmake-on-macos"
    - uses: "./.github/actions/install-gflags-on-macos"
    - uses: "./.github/actions/pre-steps-macos"
    - name: cmake generate project file
      working-directory: /Users/runner/work/encfs/encfs/rocksdb
      run: echo "skip this job"
      # TODO(yingchun): resolve the link error
#      ar: creating archive librocksdb_env_basic_test.a
#      Undefined symbols for architecture x86_64:
#          "encfs_reg", referenced from:
#                         -u command line option
#                         (maybe you meant: _encfs_reg)
#      ld: symbol(s) not found for architecture x86_64
#      clang:
#        error: linker command failed with exit code 1 (use -v to see invocation)
#      make: *** [ librocksdb_debug.8.5.3.dylib ] Error 1
#      make: *** Waiting for unfinished jobs....
#      run: ulimit -S -n `ulimit -H -n` && mkdir build && cd build && cmake -DWITH_GFLAGS=1 -DROCKSDB_PLUGINS=encfs ..
#    - name: Build tests
#      working-directory: /Users/runner/work/encfs/encfs/rocksdb
#      run: cd build && make V=1 -j4
#    - name: Run tests
#      working-directory: /Users/runner/work/encfs/encfs/rocksdb
#      run: ulimit -S -n `ulimit -H -n` && cd build && ctest -j4 -I 0,,2
    - uses: "./.github/actions/post-steps"
  build-macos-test-1:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v4
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 12.5.1
    - uses: "./.github/actions/increase-max-open-files-on-macos"
    - uses: "./.github/actions/install-cmake-on-macos"
    - uses: "./.github/actions/install-gflags-on-macos"
    - uses: "./.github/actions/pre-steps-macos"
    - name: cmake generate project file
      working-directory: /Users/runner/work/encfs/encfs/rocksdb
      run: echo "skip this job"
      # TODO(yingchun): resolve the link error
#      ar: creating archive librocksdb_env_basic_test.a
#      Undefined symbols for architecture x86_64:
#          "encfs_reg", referenced from:
#                         -u command line option
#                         (maybe you meant: _encfs_reg)
#      ld: symbol(s) not found for architecture x86_64
#      clang:
#        error: linker command failed with exit code 1 (use -v to see invocation)
#      make: *** [ librocksdb_debug.8.5.3.dylib ] Error 1
#      make: *** Waiting for unfinished jobs....
#      run: ulimit -S -n `ulimit -H -n` && mkdir build && cd build && cmake -DWITH_GFLAGS=1 -DROCKSDB_PLUGINS=encfs ..
#    - name: Build tests
#      working-directory: /Users/runner/work/encfs/encfs/rocksdb
#      run: cd build && make V=1 -j4
#    - name: Run tests
#      working-directory: /Users/runner/work/encfs/encfs/rocksdb
#      run: ulimit -S -n `ulimit -H -n` && cd build && ctest -j4 -I 1,,2
    - uses: "./.github/actions/post-steps"
