name: jobs-macos
on: [pull_request]
jobs:
  build-macos:
    runs-on: macos-11
    env:
      ROCKSDB_DISABLE_JEMALLOC: 1
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 12.5.1
    - uses: "./.github/actions/increase-max-open-files-on-macos"
    - uses: "./.github/actions/install-gflags-on-macos"
    - uses: "./.github/actions/pre-steps-macos"
    - run: ulimit -S -n `ulimit -H -n` && OPT=-DCIRCLECI make V=1 J=4 -j4 all
    - uses: "./.github/actions/post-steps"
  build-macos-test-0:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 12.5.1
    - uses: "./.github/actions/increase-max-open-files-on-macos"
    - uses: "./.github/actions/install-cmake-on-macos"
    - uses: "./.github/actions/install-gflags-on-macos"
    - uses: "./.github/actions/pre-steps-macos"
    - name: cmake generate project file
      run: ulimit -S -n `ulimit -H -n` && mkdir build && cd build && cmake -DWITH_GFLAGS=1 ..
    - name: Build tests
      run: cd build && make V=1 -j4
    - name: Run tests
      run: ulimit -S -n `ulimit -H -n` && cd build && ctest -j4 -I 0,,2
    - uses: "./.github/actions/post-steps"
  build-macos-test-1:
    runs-on: macos-11
    steps:
    - uses: actions/checkout@v3.5.0
    - uses: maxim-lobanov/setup-xcode@v1.5.1
      with:
        xcode-version: 12.5.1
    - uses: "./.github/actions/increase-max-open-files-on-macos"
    - uses: "./.github/actions/install-cmake-on-macos"
    - uses: "./.github/actions/install-gflags-on-macos"
    - uses: "./.github/actions/pre-steps-macos"
    - name: cmake generate project file
      run: ulimit -S -n `ulimit -H -n` && mkdir build && cd build && cmake -DWITH_GFLAGS=1 ..
    - name: Build tests
      run: cd build && make V=1 -j4
    - name: Run tests
      run: ulimit -S -n `ulimit -H -n` && cd build && ctest -j4 -I 1,,2
    - uses: "./.github/actions/post-steps"
