name: Check buck targets and code format
on: [pull_request]
permissions:
  contents: read

jobs:
  check:
    name: Check TARGETS file and code format
    runs-on: ubuntu-latest
    steps:
    - name: Checkout feature branch
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - uses: "./.github/actions/pre-steps"
    - name: Fetch from upstream
      working-directory: /__w/encfs/encfs/rocksdb
      run: |
        git remote add upstream https://github.com/acelyc111/encfs.git && git fetch upstream
    - name: Setup Python
      uses: actions/setup-python@v1
    - name: Install Dependencies
      run: python -m pip install --upgrade pip
    - name: Install argparse
      run: pip install argparse
    - name: Download clang-format-diff.py
      run: wget https://raw.githubusercontent.com/llvm/llvm-project/release/12.x/clang/tools/clang-format/clang-format-diff.py
    - name: Check format
      working-directory: /__w/encfs/encfs/rocksdb/plugin/encfs
      run: |
        sed -i 's/facebook\/rocksdb/acelyc111\/encfs/g' ../../build_tools/format-diff.sh
        VERBOSE_CHECK=1 ../../build_tools/format-diff.sh -c
      shell: bash
    - name: Simple source code checks
      working-directory: /__w/encfs/encfs/rocksdb/plugin/encfs
      run: ../../build_tools/check-sources.sh
